### ISSUE TITLE
Error loading page

### ISSUE THREAD

**Issue by cowboy93** [codealong/codealong#1]
I set env. and init codealong with this github.
But it makes cursor 82 error.

$ codealong init . --github-org https://github.com/codealong/
Jun 03 16:15:33.025 INFO Initializing config at ./config.yml, module: codealong::init:15
Jun 03 16:15:33.791 ERRO Error loading page: Unknown, module: codealong_github::cursor:82
Jun 03 16:15:34.536 ERRO Error loading page: Unknown, module: codealong_github::cursor:82
Jun 03 16:15:35.276 ERRO Error loading page: Unknown, module: codealong_github::cursor:82
Jun 03 16:15:35.276 INFO Initialized config at ./config.yml, module: codealong::init:18

**Comment by ghempton** [comment]
You need to specify the name of the organization, not the full url.
